library(ggplot2)
library(Hmisc)

source("gausfit.R")

am1=read.table("data/Americium_1.TKA")
am2=read.table("data/Americium_2.TKA")
co1=read.table("data/Cobalt_1.TKA")
co2=read.table("data/Cobalt_2.TKA")
co3=read.table("data/Cobalt_3.TKA")
co4=read.table("data/Cobalt_4.TKA")
co5=read.table("data/Cobalt_5.TKA")
ef1=read.table("data/Energiefenster_links.TKA")
ef2=read.table("data/Energiefenster_rechts.TKA")

am1data <- data.frame(x=1:256,y=am1[[1]],sy=sqrt(am1[[1]]))
am2data <- data.frame(x=1:256,y=am2[[1]],sy=sqrt(am2[[1]]))
co1data <- data.frame(x=1:256,y=co1[[1]],sy=sqrt(co1[[1]]))
co2data <- data.frame(x=1:256,y=co2[[1]],sy=sqrt(co2[[1]]))
co3data <- data.frame(x=1:256,y=co3[[1]],sy=sqrt(co3[[1]]))
co4data <- data.frame(x=1:256,y=co4[[1]],sy=sqrt(co4[[1]]))
co5data <- data.frame(x=1:256,y=co5[[1]],sy=sqrt(co5[[1]]))
ef1data <- data.frame(x=1:256,y=ef1[[1]],sy=sqrt(ef1[[1]]))
ef2data <- data.frame(x=1:256,y=ef2[[1]],sy=sqrt(ef2[[1]]))

plottype <- "p"
pointsize<- 0.6

weighted <- FALSE

par(mfrow=c(1,2))

cat("Americium \n\n")
cat(" links:\n")
plot(am1data$x,am1data$y,type=plottype,pch=4,xlab="Channel",ylab="Counts",cex=pointsize,xaxt="n",yaxt="n",bty="l")
with(data=am1data,expr=Hmisc::errbar(x,y,y+sy,y-sy,add=T,pch=4,type="n"))
bereich=c(10,35)
fit2=gausfit(am1data,bereich,weighted)
plotgaus(fit2,bereich)
printfitdata(fit2,"Peak 1")
bereich=c(35,65)
fit3=gausfit(am1data,bereich,weighted)
plotgaus(fit3,bereich)
printfitdata(fit3,"Peak 2")
bereich=c(65,125)
fit1=gausfit(am1data,bereich,weighted)
plotgaus(fit1,bereich)
printfitdata(fit1,"Peak 3")
title("linker Szintillator")
axis(1,at=c(0:10)*25)
axis(2,at=c(0:20)*10000)
grid()

cat("\n rechts:\n")
plot(am2data$x,am2data$y,type=plottype,pch=4,xlab="Channel",ylab="Counts",cex=pointsize,xaxt="n",yaxt="n",bty="l")
with(data=am2data,expr=Hmisc::errbar(x,y,y+sy,y-sy,add=T,pch=4,type="n"))
bereich=c(10,35)
fit=gausfit(am2data,bereich,weighted)
plotgaus(fit,bereich)
printfitdata(fit,"Peak 1")
bereich=c(40,65)
fit=gausfit(am2data,bereich,weighted)
plotgaus(fit,bereich)
printfitdata(fit,"Peak 2")
bereich=c(75,125)
fit=gausfit(am2data,bereich,weighted)
plotgaus(fit,bereich)
printfitdata(fit,"Peak 3")
title("rechter Szintillator")
axis(1,at=c(0:10)*25)
axis(2,at=c(0:20)*10000)
grid()

par(mfrow=c(2,2))

plot(co2data$x,co2data$y,type=plottype,pch=4,xlab="Channel",ylab="Counts",cex=pointsize,xaxt="n",yaxt="n",bty="l")
with(data=co2data,expr=Hmisc::errbar(x,y,y+sy,y-sy,add=T,pch=4,type="n"))
bereich=c(150,250)
fit=gausfit(co2data,bereich,weighted)
plotgaus(fit,bereich)
title("linker Szintillator, Orientierung 1")
axis(1,at=c(0:10)*25)
axis(2,at=c(0:11)*10000)
grid()

plot(co3data$x,co3data$y,type=plottype,pch=4,xlab="Channel",ylab="Counts",cex=pointsize,xaxt="n",yaxt="n",bty="l")
with(data=co3data,expr=Hmisc::errbar(x,y,y+sy,y-sy,add=T,pch=4,type="n"))
bereich=c(175,250)
fit=gausfit(co3data,bereich,weighted)
plotgaus(fit,bereich)
bereich=c(10,30)
fit=gausfit(co3data,bereich,weighted)
plotgaus(fit,bereich)
title("rechter Szintillator, Orientierung 1")
axis(1,at=c(0:10)*25)
axis(2,at=c(0:11)*100000)
grid()

plot(co5data$x,co5data$y,type=plottype,pch=4,xlab="Channel",ylab="Counts",cex=pointsize,xaxt="n",yaxt="n",bty="l")
with(data=co5data,expr=Hmisc::errbar(x,y,y+sy,y-sy,add=T,pch=4,type="n"))
bereich=c(150,250)
fit=gausfit(co5data,bereich,weighted)
plotgaus(fit,bereich)
title("linker Szintillator, Orientierung 2")
axis(1,at=c(0:10)*25)
axis(2,at=c(0:11)*20000)
grid()

plot(co4data$x,co4data$y,type=plottype,pch=4,xlab="Channel",ylab="Counts",cex=pointsize,xaxt="n",yaxt="n",bty="l")
with(data=co4data,expr=Hmisc::errbar(x,y,y+sy,y-sy,add=T,pch=4,type="n",cex=0.2))
bereich=c(150,250)
fit=gausfit(co4data,bereich,weighted)
plotgaus(fit,bereich)
title("rechter Szintillator, Orientierung 2")
axis(1,at=c(0:10)*25)
axis(2,at=c(0:11)*20000)
grid()

par(mfrow=c(1,2))

plot(ef1data$x,ef1data$y,type=plottype,pch=4,xlab="Channel",ylab="Counts",cex=pointsize,xaxt="n",yaxt="n",bty="l")
with(data=ef1data,expr=Hmisc::errbar(x,y,y+sy,y-sy,add=T,pch=4,type="n"))
bereich=c(135,188)
fit=gausfit(ef1data,bereich,weighted)
plotgaus(fit,bereich)
title("linker Szintillator")
axis(1,at=c(0:10)*25)
axis(2,at=c(0:11)*2000)
grid()

plot(ef2data$x,ef2data$y,type=plottype,pch=4,xlab="Channel",ylab="Counts",cex=pointsize,xaxt="n",yaxt="n",bty="l")
with(data=ef2data,expr=Hmisc::errbar(x,y,y+sy,y-sy,add=T,pch=4,type="n"))
bereich=c(4,35)
fit=gausfit(ef2data,bereich,weighted)
plotgaus(fit,bereich)
title("rechter Szintillator")
axis(1,at=c(0:10)*25)
axis(2,at=c(0:11)*200)
grid()